### ISSUE TITLE
Variable Clipboard stopped working in v3.4

### ISSUE THREAD

**Issue by cdss-janek** [thundernest/quicktext#207] opened 2020-11-10 18:10 UTC
If you copy text **outside** ThunderBird, [[CLIPBOARD]] is empty.
If you copy text **inside** ThunderBird, [[CLIPBOARD]] works fine.

**Comment by jobisoft** [comment] 2020-11-10 18:15
@SamuelPlentz : Do we have to back out https://github.com/jobisoft/quicktext/pull/183 ?

**Comment by SamuelPlentz** [comment] 2020-11-11 06:50
I think we need a small fix.

I could reproduce it with this HTML-template:
`[[CLIPBOARD]]`

Then copy some plain text from Notepad. And apply the template > nothing happens.

It works when I have a TEXT-template or if I copy formatted text from Microsoft Word.

@cdss-janek:
Can you confirm the bug only exists when creating a HTML-template.
Can you confirm the bug only exists when copying plain text. (From what source are you copying?)

**Comment by cdss-janek** [comment] 2020-11-11 12:23
@SamuelPlentz 
Yes, you are right. It's not about inside/outside TB. It's not working with plain text.
My source is for example js script on webpage that copies a parcel number to clipboard (plain text).

**Comment by SamuelPlentz** [comment] 2020-11-11 13:52
Only the procedure `process_clipboard` should be affected (not the whole changes of #183).
It looks like we can't access the HTML-Clipboard. We should fall back to the Text-Clipboard in this case.

Will look into this later.

**Comment by SamuelPlentz** [comment] 2020-11-14 21:17
Could you please confirm, that the attached version solves the problem?
[quicktext clipboard.zip](https://github.com/jobisoft/quicktext/files/5541474/quicktext.clipboard.zip)

**Comment by cdss-janek** [comment] 2020-11-15 10:07
Yes, it solves the problem. Thank you.

**Comment by jobisoft** [comment] 2021-01-16 10:54
Released as v3.5.

**Closed as completed by jobisoft** 2021-01-16 10:54 UTC
