### ISSUE TITLE
[[HEADER=to|...]] (or HEADER=cc) does not work

### ISSUE THREAD

**Issue by yimir0** [thundernest/quicktext#314] opened 2022-07-04 12:20 UTC
Since last 2 updates of thunderbird, those variables does not work anymore: the email I configured does not shows in the TO, CC or BCC fields.
Thanks in advance for any help

**Comment by SamuelPlentz** [comment] 2022-07-04 12:23
Duplicate of: #307 (Solution inside.)

**Closed as completed** 2022-07-04 12:50 UTC

**Comment by jobisoft** [comment] 2022-07-04 12:52
An updated version 5.2 has been released and should be shipped automatically to users soon.
