### ISSUE TITLE
Make the "Parancsfájl hozzáadása" button bigger so all the text is inside the button

### ISSUE THREAD

**Issue by ovari** [thundernest/quicktext#58] opened 2019-02-21 08:56 UTC
Please make the "Parancsfájl hozzáadása" button bigger so all the text fits inside the button with the hu locale.

Image below shows the situation with Linux Mint 19.1 Cinnamon

Thank you

![image](https://user-images.githubusercontent.com/17465872/53156034-8595a980-3612-11e9-8836-0945290a0f8a.png)

**Comment by SamuelPlentz** [comment] 2020-02-11 00:18
Have looked into it.

When I changed my language to the "hu" locale I can't reproduce the bug on Windows 10. Here the text in the script side panel fits nicely into the 200px:
![Image](https://user-images.githubusercontent.com/1890854/74201519-52f12080-4c6a-11ea-8702-be308aeb1cd5.png)

The file "chrome\content\settings.xul" always contained 200px width for the script side panel. So IMO it must be some rendering problem in Linux Mint.

The side panel in the screenshot above only has a 156px width. It looks like additional 25px would solve the problem. But perhaps the "200px" value is fully ignored, so increasing it to "225px" won't work either.

@ovari:
1. Does the problem still exist in the current versions of Thunderbird, Quicktext and Linux Mint?
2. Could you try if increasing all values from "200px" to "225px" in the file "chrome\content\settings.xul" solves the problem? 

If the 2 points above won't help I would propose to close as won't fix.

**Comment by ovari** [comment] 2020-02-14 09:38
Linux Mint 19.3 Cinnamon 64-bit
Thunderbird 68.4.1 (64-bit)
Quicktext 2.12

1. Problem no longer exists in the current versions of Thunderbird, Quicktext and Linux Mint as shown below:

![image](https://user-images.githubusercontent.com/17465872/74519191-5dacfd80-4f69-11ea-9fac-a7c950a5432b.png)

2. Did not do your step 2 the problem no longer exists.

Thank you

Strange that now the heading `Cím` and `Parancsfájl` have a white background (should be grey or transparent?). This is in the other tabs too:

![image](https://user-images.githubusercontent.com/17465872/74519496-e88df800-4f69-11ea-8e9a-1d09c6837f5d.png)

Can this be fixed?

Thank you

**Comment by SamuelPlentz** [comment] 2020-02-14 23:03
> Can this be fixed?

No. It seems to be another rendering problem, that is not (easily) fixable.
Here it is fine:
![Image](https://user-images.githubusercontent.com/1890854/74201519-52f12080-4c6a-11ea-8702-be308aeb1cd5.png)

It is caused by the line `background-color: -moz-Field;` from `quicktext.css`:
``` css
groupbox > .box-title > .header {
  font-weight: bold;
  margin-top: -2px;
  margin-bottom:1em;
  margin-inline-start: 3px;
  padding-right: 3px;
  padding-left: 3px;
  background-color: -moz-Field;
}
```

When one would omit this line in the Windows 10 version the group box will strike through the text.

**Comment by jobisoft** [comment] 2020-02-15 06:57
Yes, I tried to fix the broken groupbox caption in windows and it looks like it is now broken in Linux and MacOS.

I will revert and load the "fix" only for windows.

**Comment by ovari** [comment] 2020-02-15 07:10
Please accept https://github.com/thundernest/quicktext/pull/146

**Closed as completed** 2020-02-15 15:56 UTC
Labels: need feedback
