### ISSUE TITLE
[[CLIPBOARD]] does not working

### ISSUE THREAD

**Issue by Heliophob** [thundernest/quicktext#84] opened 2019-10-07 20:33 UTC
Hello, 

After a Thunderbird-Upate on V. 68.1.1 the function "Clipboard" does not work anymore.

Best Regards

**Comment by au7oma7** [comment] 2019-10-31 12:25
"Clipboard" also doesn't work on 68.2.0 32bit. Windows 7 x64

**Comment by jobisoft** [comment] 2019-11-01 12:19
Fix for this is posted here:
https://github.com/thundernest/quicktext/issues/85#issuecomment-548768594

Can you check?

**Comment by au7oma7** [comment] 2019-11-01 15:33
Seems fixed now. Tested on 68.2.1 x64 and x86.
Good job, thanks!

**Comment by jobisoft** [comment] 2019-11-01 16:55
Available on ATN:
https://addons.thunderbird.net/en-US/thunderbird/addon/quicktext/versions/?page=1#version-2.6

**Comment by caseneuve** [comment] 2023-07-24 08:08
Looks like the `[[CLIPBOARD]]` tag is not working again in Thunderbird 115.0.1 (using v5.6 on Arch Linux).

**Comment by SamuelPlentz** [comment] 2023-07-25 13:08
Yes this should be reopened. I can reproduce the issue in Windows 10 and Thunderbird 115.0.1.

Here line 750 fails with:
```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITransferable.getTransferData]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://quicktext/content/modules/wzQuicktextVar.jsm :: process_clipboard :: line 751"  data: no]
```

https://github.com/jobisoft/quicktext/blob/8af51b491ccc26ff55ecfc2372722f2b10539475/chrome/content/modules/wzQuicktextVar.jsm#L703-L765

**Comment by jobisoft** [comment] 2023-07-25 13:12
Can someone replace text/unicode with text/plain or check searchfox what TB uses and try that?

**Comment by SamuelPlentz** [comment] 2023-07-25 13:14
IIRC I just tried that and it still failed.

**Comment by SamuelPlentz** [comment] 2023-07-25 13:26
I double checked it. Replacing ```text/unicode``` by ```text/plain``` twice works. Apparently I also changed something else previously.

The clipboard was only broken for TEXT-templates (line 750), HTML-templates worked fine (line 727).

**Comment by SamuelPlentz** [comment] 2023-07-25 13:34
This pull request should solve the problem: #363.

**Closed as completed** 2023-07-25 14:53 UTC
Labels: bug
