### ISSUE TITLE
Word wrap breaks in Thunderbird 102.15. with Quicktext 5.10

### ISSUE THREAD

**Issue by GrantHorizons** [thundernest/quicktext#376] opened 2023-08-31 23:38 UTC
Word wrap in HTML, centering of "centered" photos and text body broken - doesn't wrap properly, lines the entire width of my THREE monitors before it wraps, even with the Tbird compose window 300 pixels wide. Turning off Quicktext fixes it instantly. Reverted to 5.8, and it's fine. 5.10 a PROBLEM.

**Comment by jobisoft** [comment] 2023-08-31 23:42
Dupe of #374 
(please try https://github.com/jobisoft/quicktext/issues/374#issuecomment-1701232040)

**Closed as completed by jobisoft** 2023-08-31 23:42 UTC
