### ISSUE TITLE
right click mess

### ISSUE THREAD

**Issue by lubu63** [thundernest/quicktext#90] opened 2019-10-30 14:29 UTC
Quicktext is messing my right click menu by hiding all items
![quicktext](https://user-images.githubusercontent.com/57185170/67866976-06099400-fb2a-11e9-88d2-08ae74e68ba2.jpg)

**Comment by jobisoft** [comment] 2019-10-30 14:32
True, never noticed that.

For the time being you need to disable the "show quicktext on right click" option.

**Comment by lubu63** [comment] 2019-10-30 14:45
No way, is messed even disabling it. Not a big problem for me since I'm using shortcuts but just to let you know
![quicktext 2](https://user-images.githubusercontent.com/57185170/67868397-39e5b900-fb2c-11e9-951c-fa9e53184fec.jpg)

**Comment by jobisoft** [comment] 2019-10-30 14:55
100% sure, that this is caused by QuickText ONLY? Can you disable all other addons except Quicktext? If error disappears, activate your other addons 1-by-1 to see which causes this together with Quicktext?

**Comment by lubu63** [comment] 2019-10-30 15:14
Yes, I've disabled everything but QuickText and I've this error, enabled all addosn except QuickText and no error. I'm quite sure this error wasn't present before updating to 68+ version of Thunderbird because I used to right click for another addon is not compatible with this new versions (I'm on 71 beta) and everything was fine.

**Comment by jobisoft** [comment] 2019-10-30 15:17
Oh, I do not support TB71. How did you get it installed?

**Comment by lubu63** [comment] 2019-10-30 15:22
Updating by the beta channel. I try to downgrade and let you know

**Comment by jobisoft** [comment] 2019-10-30 15:34
I limited its usage to TB68 just now. It was set to "open end" which was wrong.

**Comment by jobisoft** [comment] 2019-11-01 11:43
Closing this as invalid, as TB71 is not supported

**Closed as completed by jobisoft** 2019-11-01 11:43 UTC
