### ISSUE TITLE
Inserting template fails before following text

### ISSUE THREAD

**Issue by jonnyhopkins** [thundernest/quicktext#388] opened 2023-11-14 10:32 UTC
Specifically, if I attempt to insert a template after pressing return, while there is text on a new line below (e.g. insert signature at the end of a reply), Quicktext seems to insert a backspace instead.  All other situations seem to be fine: insert at end of email; insert at end of sentence; insert at start of email.
I'm running the latest version of Quicktext and Thunderbird on Linux Mint 21.  Happy to provide more info if necessary.

Edit: this only seems to affect html templates.

**Comment by jonnyhopkins** [comment] 2023-11-14 10:42
Reply to add: this only affects html templates, plain text templates seem to be fine.

**Comment by jobisoft** [comment] 2023-11-14 13:08
Dupe of https://github.com/jobisoft/quicktext/issues/380

**Closed as completed by jobisoft** 2023-11-14 13:08 UTC
