### ISSUE TITLE
Quicktext doesn't work after update 78

### ISSUE THREAD

**Issue by sbl2020** [thundernest/quicktext#177] opened 2020-09-22 09:12 UTC
Hello,

Since the update to 78, the Quicktext add-on no longer works properly for me.
On the settings page, the fields in which you can change the templates are missing:

![grafik](https://user-images.githubusercontent.com/71697516/93863714-230c0000-fcc4-11ea-8597-577154f74bc5.png)

This means that no new templates can be created. Old cannot be changed.
What could be the reason therefore?

greetings

**Comment by michaldolensky** [comment] 2020-09-22 18:26
Hello,
it seems that you are editing group rather than template in the picture. What happens if you click on "fgsfs" template? 

I tried to create new template using latest Thunderbird (78.2.2) and Quicktext v3.2 and it worked as it should. 

Pardon me if I misunderstood the question.

**Comment by hannesss** [comment] 2020-09-24 18:42
I wanted to create an issue with the same title. Not sure if it is the correct place, but I'll comment it here.

## Problem

Using Quicktext 3.2 and Thunderbird 78.2.2

The addon no longer works. It no longer appears in the menu and the tabulator shortcuts do not apply

![grafik](https://user-images.githubusercontent.com/37758997/94185188-493cc600-fea5-11ea-9bb1-d21748ee14ef.png)

When deactivating an activating the addon it works again. It appears in the menu and tabulator shortcuts apply.

![grafik](https://user-images.githubusercontent.com/37758997/94185293-683b5800-fea5-11ea-9e6b-15d413416883.png)

However, when closing Thunderbird and starting it again, the bug appears again ...

So my current workaround is to disable/enable Quicktext every time I start Thunderbird.

**Comment by jobisoft** [comment] 2020-09-24 18:43
Try it in a fresh profile please.

**Comment by SamuelPlentz** [comment] 2020-09-24 18:50
Probably related with #167.
You could try to disable other addons and deactivate the masterpassword if set.

**Comment by hatsumatsu** [comment] 2020-10-05 15:02
Same here, selecting/adding a template does not show the message field and the rest of the settings only its title. 
I tried re-installing TB (using the existing profile) but no luck.

**Comment by jobisoft** [comment] 2020-10-05 15:05
Comming back to the screenshot provided: This is group title edit mode. You need to select a template to edit a template.

**Comment by hatsumatsu** [comment] 2020-10-05 16:36
@jobisoft This is how the pane looks for me when in template mode:

<img width="401" alt="Screenshot 2020-10-05 at 18 34 38" src="https://user-images.githubusercontent.com/3452400/95107042-a7856680-0739-11eb-8bb3-a8946bce9df4.png">

Using Thunderbird Version 78.3.1 (64-bit) on MacOS 10.14.6.

**Comment by SamuelPlentz** [comment] 2020-10-05 16:54
Probably related with #167.
Could you please try to disable all other addons and deactivate the masterpassword if set.

**Comment by hatsumatsu** [comment] 2020-10-05 18:52
@jobisoft In my case there are no other addons present and no master password set.

**Comment by jobisoft** [comment] 2020-10-05 19:15
:-( Are there other Mac users who can confirm this? Or are there Mac users, where QT woks as expected?

**Comment by hatsumatsu** [comment] 2020-10-06 10:09
@jobisoft I just checked TB's error console and found this error popping up when switching to the template view in  quicktext's settings: 

`````
settings.js:786

Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]", result: 2147500037, filename: "chrome://quicktext/content/settings.js", lineNumber: 786, columnNumber: 0, data: null, stack: "pickText@chrome://quicktext/content/settings.js:786:90\nonselect@chrome://quicktext/content/settings.xhtml:1:11\nMozTreeChildren/<@chrome://global/content/elements/tree.js:69:28\n", location: XPCWrappedNative_NoHelper }

`````

**Comment by hatsumatsu** [comment] 2020-10-06 10:29
@jobisoft I just checked TB's error console and found this error popping up when switching to the template view in  quicktext's settings: 

`````
settings.js:786

Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]", result: 2147500037, filename: "chrome://quicktext/content/settings.js", lineNumber: 786, columnNumber: 0, data: null, stack: "pickText@chrome://quicktext/content/settings.js:786:90\nonselect@chrome://quicktext/content/settings.xhtml:1:11\nMozTreeChildren/<@chrome://global/content/elements/tree.js:69:28\n", location: XPCWrappedNative_NoHelper }

`````

**Comment by SamuelPlentz** [comment] 2020-10-06 18:06
Thats a nice hint! This is the referred line:
https://github.com/jobisoft/quicktext/blob/60db00b2fbb276a2720536fa9f11085112d17e19/chrome/content/settings.js#L786

Looks like either `document.getElementById('select-shortcutModifier').value` is not translated to your language correctly.
Or it does contain an unexpected string, not translated to any language.

1. What is your shortcut modifier? (Quicktext Settings > General > "use for shortcuts"-Dropdown)
2. Could you try if this version works for you? (remove the ".zip" extension and install it)
[quicktext-3.3a1-tb.xpi.zip](https://github.com/jobisoft/quicktext/files/5335727/quicktext-3.3a1-tb.xpi.zip)
3. If it works what does this version output next to shortcut here: (Quicktext Settings > Templates > Shortcut)
![Bild](https://user-images.githubusercontent.com/1890854/95242148-0f59b100-080f-11eb-9813-f8a378e4b37b.png)

**Comment by jobisoft** [comment] 2020-10-06 18:12
@SamuelPlentz : thanks for your lead in this issue.

**Comment by SamuelPlentz** [comment] 2020-10-06 18:14
For reference, I changed that line
``` Javascript
document.getElementById('label-shortcutModifier').value = gQuicktext.mStringBundle.GetStringFromName(document.getElementById('select-shortcutModifier').value +"Key") +"+";
```

Like this:
``` Javascript
document.getElementById('label-shortcutModifier').value = '"' + document.getElementById('select-shortcutModifier').value + '"';
```

Couldn't get an Alert to work.

**Comment by jobisoft** [comment] 2020-10-06 18:29
to dump some info to the console, you can always use `console.log("bla blub");`

**Comment by hatsumatsu** [comment] 2020-10-07 07:20
@SamuelPlentz 

> * What is your shortcut modifier? (Quicktext Settings > General > "use for shortcuts"-Dropdown)

Turns out this settings field was empty/unset in my case. As soon as I select a value the template settings start to work again.

Side note: The problem could indeed be translation-based since I initially use a localized version of TB and only recently switched to the english version by "installing over" my existing one.

**Comment by SamuelPlentz** [comment] 2020-10-07 17:50
Thanks for your input. Could reproduce the behavior if the value is undefined.
Created a patch to reset the value of mShortcutModifier to "alt", if it has not a valid value.

Should be solved by #186.

**Comment by EmmyGraugans** [comment] 2020-10-08 07:08
> :-( Are there other Mac users who can confirm this? Or are there Mac users, where QT woks as expected?

I had that problem right after installing Thunderbird 78.2.1 - it went away after a little while and a few restarts (might also have been an uninstall-and-reinstall of Quicktext among the things I tried...) Sorry that I cannot be more specific. At least I can definitely say, I *had* the problem and I *don't* have it any more.

(and my answer was a bit late, I guess - sorry for the noise)

**Comment by jobisoft** [comment] 2020-10-08 07:47
@SamuelPlentz : I do not know @EmmyGraugans environment, but there was also an incompatibility to Enigmail, which has been fixed with an update for Enigmail on Oktober 1st. (That bug also killed multiple add-ons, not just QT). So reproducibility is not always possible.

**Comment by PCJones** [comment] 2020-10-19 10:52
I'm having the exact same problem. Thunderbird 78 and german language Win 10. No other add-ons or master password is set.

**Comment by SamuelPlentz** [comment] 2020-10-19 11:57
Could you try the [Quicktext 3.3 pre release](https://github.com/jobisoft/quicktext/issues/167#issuecomment-709144213) or [Quicktext 3.4 pre release](https://github.com/jobisoft/quicktext/issues/167#issuecomment-710672245) together with TB 78.3.3.

**Comment by andreasklostermaier** [comment] 2020-10-20 13:17
Had the same problem today after the 78.3.3 update. It persisted through Thunderbird restarts, but it solved itself after I manually deactivated and activated the Quicktext add-on (without leaving Thunderbird).

**Comment by SamuelPlentz** [comment] 2020-10-26 19:23
Could be closed now. (fixed original issue - the other problems are probably related to #167)

**Closed as completed** 2020-10-26 19:46 UTC
