### ISSUE TITLE
Not compatible with TB 91

### ISSUE THREAD

**Issue by slabbi** [thundernest/quicktext#259] opened 2021-08-15 13:13 UTC
Hi,

Quicktext is not compatible with TB 91. It is not possible to insert templates and the configuration screen is messed up.

**Comment by slabbi** [comment] 2021-08-15 13:19
Sorry, did not see the 4.0 release.

**Comment by slabbi** [comment] 2021-08-15 13:52
Damn, closed too early.

Does not work in TB 91. Configuration menu appears correctly but it is not possible to insert any template.

**Comment by jobisoft** [comment] 2021-08-16 10:42
I cannot reproduce your findings. Did you add a group first? Running fine here with TB91

**Comment by SamuelPlentz** [comment] 2021-08-16 10:42
It is fine here. Could you create a new profile with only the Quicktext extension?
Does it work there?

**Comment by slabbi** [comment] 2021-08-16 12:23
After some testing: When you have defined an attachment the text will not be inserted.

**Comment by slabbi** [comment] 2021-08-16 12:25
Didn't recognize that it is the attachment that causes this bug because most of my shortcuts have one.

**Comment by jobisoft** [comment] 2021-08-16 17:19
Confirming the attachment bug.

**Comment by jobisoft** [comment] 2021-08-16 21:06
[quicktext.xpi](https://github.com/jobisoft/quicktext/files/6995412/quicktext.zip)

Are you able to install this version? Does that fix the reported issue?

**Comment by slabbi** [comment] 2021-08-17 13:50
Sorry, currently I cannot check it because I have no access to my systems.

**Comment by SamuelPlentz** [comment] 2021-08-17 16:07
I can confirm the bug present in version 4.0 when using attachments.
I can confirm the bug fixed in version 4.1 (the file you provided here) when using attachments.

**Comment by jobisoft** [comment] 2021-08-17 16:08
Already released to ATN.

**Closed as completed by jobisoft** 2021-08-17 16:08 UTC
