### ISSUE TITLE
2.1 version don't retrieve the content of an old installation disabled (Td 68)

### ISSUE THREAD

**Issue by Mozinet-fr** [thundernest/quicktext#79] opened 2019-08-29 10:34 UTC
I installed Thunderbird 68, the Quicktext extension has been disabled. I then installed Quicktext 2.1 from addons.thunderbird.net. After a Thunderbird restart, Quicktext is now empty.

Windows 7 64bit, French

**Comment by jobisoft** [comment] 2019-08-29 10:40
I did some update tests,to check if the data survives and it did work. Do not know why it did not for you.     

It souds like, you did not use the official ATN version of quicktext before (because that would have auto-updated itself)?

**Comment by Mozinet-fr** [comment] 2019-08-29 12:41
Yes, I have been using Quicktext for a long time.

**Comment by jobisoft** [comment] 2019-08-30 15:46
Can you retry with the version available here:
https://github.com/thundernest/quicktext/issues/73#issuecomment-526650183

Any difference? Can you send me your quicktext config files via email?

**Comment by Mozinet-fr** [comment] 2019-08-30 16:23
No difference. XML files are pretty empty. I sent them to you.

**Comment by jobisoft** [comment] 2019-08-30 16:28
Hm, those files are indeed empty, so Quicktext cannot load anything. 

Quicktext does not save anything to the file, if you do not hit the "save" button. So just by starting TB68, yout files are not changed. How could these files end up being empty?

Do you have any other version / profile / backup?

**Comment by Mozinet-fr** [comment] 2019-08-30 16:47
I found old template files saved in 2014. The import does not succeed. Quicktext is always empty. The files are 17 and 24 KB.

**Comment by jobisoft** [comment] 2019-08-30 16:52
make a backp of those, so you do not loose them. can you send them to me as well?

**Comment by jobisoft** [comment] 2019-08-30 17:38
I renamed the file "templates.xml" and moved it into the quicktext folder of my profile and started TB68 with Quicktext 2.3: Everything is there. I also imported the file (in another profile) and it also worked without error.

Please make sure, that you really have Quicktext 2.3 installed.

**Comment by jobisoft** [comment] 2019-08-30 18:25
So it looks like it is working for you now. Great! Can I close this?

**Comment by Mozinet-fr** [comment] 2019-08-31 09:59
We found a workaround but I didn't recover my data. The bug still exists. I have to make do and will find my canned texts in my emails.

**Comment by jobisoft** [comment] 2019-08-31 10:46
I am sorry, I cannot follow you. You renamed your backup "templates.xml" which is the default filename for the templates file and it loaded your file. This is exactly how it is supposed to work.

I do not see this as a workaround. What bug still exists? Please be a little more verbose.

You still have not answered, what version of quicktext you were using in TB60 and where you got that from. (https://github.com/thundernest/quicktext/issues/79#issuecomment-526129913)

**Comment by Mozinet-fr** [comment] 2019-08-31 11:16
I was on the latest Thunderbird 60 (the 60.8 I think). I installed the 68 from thunderbird.net website. My Quicktext data is gone and the import feature does not recover my latest backup. The workaround solution was to replace templates.xml in the profile folder to recover the data from the latest backup.

**Comment by jobisoft** [comment] 2019-08-31 11:27
I asked about the version of Quicktext, not Thunderbird. 

I volunteered to update Quicktext from a state that the original author released under open source. I am not the original author. There are a lot of different versions out there which i have no control over. I could only test and verify the update from my own version I released for TB60.

Can you give more details for:
 > the import feature does not recover my latest backup

I was able to import your file just fine.

**Comment by Mozinet-fr** [comment] 2019-08-31 11:32
I presume I had version 1.5 on Thunderbird 60, but I can't ensure that. After the update to Thunderbird 68, I installed the Thunderbird 68 compatible version on ATN. This had not recovered the data. The internal import functionality did not load my backup file.

**Comment by jobisoft** [comment] 2019-08-31 11:45
I remember testing the import and it worked for me. As I considered this bug closed, I deleted all emails. Can you send your backup again?

**Comment by jobisoft** [comment] 2019-09-01 09:50
Sorry I cannot reproduce that. I manually removed all entries in quicktext using the remove button, until it was empty again:
![image](https://user-images.githubusercontent.com/5830621/64074646-6907b780-ccae-11e9-8ac0-cc0b8da71e7e.png)

Than I imported you file "as-is" via the import template button:

![image](https://user-images.githubusercontent.com/5830621/64074653-86d51c80-ccae-11e9-86d8-bc9b00ce511d.png)

and *bam* all your enteries where back:

![image](https://user-images.githubusercontent.com/5830621/64074666-9bb1b000-ccae-11e9-92ee-d33871552f60.png)


I used the official version 2.3
https://addons.thunderbird.net/addon/quicktext/versions/

I tend to close this now as fixed.

**Comment by Mozinet-fr** [comment] 2019-09-01 11:11
Yes, I can't reproduce the problem. Now the export and import features work.

Thunderbird 68.0, Quicktext 2.3.

**Closed as completed** 2019-09-01 11:37 UTC
Labels: bug
