### ISSUE TITLE
Bug: FROM template does not work with most types

### ISSUE THREAD

**Issue by Gakai** [thundernest/quicktext#23] opened 2018-07-30 17:48 UTC
The `[[FROM=type]]` template returns only empty strings for most `types`.
I tested `email`, `firstname`, `lastname`, `fullname`, `displayname` and `nickname` as listed explicitly in the wiki, but only `email` yields a usable result.

I suppose this is related to [nsIAbCard](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIAbCard), as it states, that _Properties aren't stored anymore on the card, except for a handful of them._

**Comment by jobisoft** [comment] 2018-08-01 06:09
I cannot confirm. 

The From template is using the email address of the email identity used to send the email and is searching the "personal addressbook" for an entry with that email address and is taking the data from there. 

Can I close this?

**Comment by alie2n** [comment] 2018-09-20 11:44
Is there a way to force the template to use the data provided in the identity? Getting the data from the adressbook does not work for me here.
Or do you have an idea on how to access the properties of the current compose window using a script? I tried to get this working with no positive result as I don't know how to access the gCurrentIdentity object which would help me a long way I think.

**Comment by juup** [comment] 2019-01-16 17:10
Same issue here with TB 60.4.0 on Arch.
On Windows and LinunxMint FROM is working fine.

**Comment by juup** [comment] 2019-02-04 20:16
Should I open a new issue or will this issue be set to open?

**Comment by jobisoft** [comment] 2019-02-04 20:18
As I cannot reproduce this, it will be hard to fix.

**Comment by juup** [comment] 2019-02-04 20:19
How can I help?

**Comment by jobisoft** [comment] 2019-02-04 21:49
If you can, analyze the code and try to pinpoint where and why this goes wrong. At what line do Arch and Mint do not behave the same (different var content etc.). You will need to unpack the XPI and add debug outputs via

`Services.console.logStringMessage("hello world");`

or use the debuger to single step through the code (but using the debugger *could* trigger different behaviour)

**Comment by juup** [comment] 2019-02-05 17:18
I've never used a debugger, so I need to look into some tutorials before. Do you know some good links?

For now I can offer a workaround: As you posted before: fill contacts in the "personal addressbook" with the email, for which FROM should work. 
On all systems I use Cardbook and on Windows FROM does work without contacts in the "personal addressbook". On Linux Mint my "personal addressbook" was still filled with old addresses (didn't recognized before, sorry) and they are needed there like on Arch.

**Comment by juup** [comment] 2019-02-05 17:21
TO works fine with Cardbook on all systems.

**Comment by jobisoft** [comment] 2019-02-05 17:35
you sure it querries the cardbook address book and not the TB adressbook? I do not see any API for cardbook Access....

**Comment by juup** [comment] 2019-02-05 18:27
Properly none is right. :-)
It looks like the NAME in front of the Email (NAME<emailadress@domain.com>) is taken. The NAME is automatically set, when I enter an email which is in Cardbook.
Does this make sense?

**Comment by juup** [comment] 2019-02-05 18:29
If yes: is it possible to use the NAME from sender, when the emailadress is not in the TB addressbook.

**Comment by juup** [comment] 2019-02-05 18:31
`NAME<emailadress@domain.com>`
was mentioned in the post before.

**Closed as completed** 2019-12-02 15:07 UTC
Labels: bug
