### ISSUE TITLE
number keys doesn't work after [alt] + [tab] linux

### ISSUE THREAD

**Issue by s8huth** [thundernest/quicktext#81] opened 2019-09-17 09:14 UTC
when i write a new mail and using [alt] + [tab] to change the windows and back to thunderbird, no number keys are working any more. i have to tap the [alt]-key again, thus the number keys work again. it seems that using the [alt]-key with [alt] + [tab] get the conflict.

regards
s8huth

linux mint 19.2
thunderbird 68.1

**Comment by jobisoft** [comment] 2019-09-21 11:44
I cannot reproduce that in windows :-( 

I have a template bound to ALT+1 and I can do ALT+1 , ALT+TAB (multiple times), ALT+1 and it works.

When I tab the windows I have to let go of ALT to actually switch to the selected window, otherwise I remain in the "select window screen". So I do not keep ALT key down all the time, when I do the above sequence. How is that on linux?

**Comment by jobisoft** [comment] 2019-09-28 10:50
status?

**Comment by s8huth** [comment] 2019-09-30 21:35
hi,

sorry, for the delay. i need to keep down the alt-key always to change
windows in linux (alt+tab). after installing the new update of quicktext
yesterday nothing has changed on this.

regards

**Comment by s8huth** [comment] 2019-10-01 09:59
hi again,

i deactivated the function "Erweiterten Modus für Tastaturkürzel verwenden" and the problem was solved. Is this function buggy?

regards

**Comment by jobisoft** [comment] 2019-10-01 10:01
I have no idea what that function does (I am just the maintainer). Is there an explenation somewhere, what it SHOULD do?

**Comment by jobisoft** [comment] 2019-10-02 19:45
That options is changing the insert behaviour. If I have 3 templates with the following shortcuts
 - "CTRL + 1"
 - "CTRL + 2"
 - "CTRL + 34"

**advMode off:** 
- CTRL down
- 1 down
- insert action (as long as 1 is down)
- 1 up
- 2 down 
- insert action ( as long as 2 is down)
- 2 up
- CTRL up

but 

- CTRL down
- 3 down + up 
- 4 down + up
- CTRL up

will not insert anything.

**advMode on:** 

- CTRL down
- 1 down + up
- CTRL up
- insert action

and

- CTRL down
- 3 down + up
- 4 down + up
- CTRL up
- insert action

So your szenario was:

advMode on:
 - ALT down
 - TAB down + up
 - number down + up
 - ALT up

That would then not trigger your shortkey, as the TAB key messed up the sequence.

However, on my system TB68 I am not able to activate the advanced mode with ALT. How did that happen?

Can we close this?

**Closed as completed** 2019-10-04 09:55 UTC
