### ISSUE TITLE
Quicktext is incompatible with Thunderbird 68.3.1

### ISSUE THREAD

**Issue by jussiep** [thundernest/quicktext#118] opened 2020-01-09 20:26 UTC
I just upgraded to Thunderbird 68.3.1 only to find that this wonderful addon is no longer compatible with the new version of Thunderbird.  Here's hoping this can be fixed?

**Comment by jobisoft** [comment] 2020-01-09 20:38
Duplicate of #116 (and not true).

**Closed as completed by jobisoft** 2020-01-09 20:38 UTC
