### ISSUE TITLE
Re-import of exported and edited xml-file not possible

### ISSUE THREAD

**Issue by CargoB** [thundernest/quicktext#28] opened 2018-08-29 09:40 UTC
Happy, that Quicktext is not dead. Thanx!
But I have a problem now:
After exporting some templates created in the quicktext settings editor I opened the xml file in a few extern editors (dreamweaver cs6, notepad++, EditPad Lite7) to make  a few changings before importing the xml file into some other clients in our office.
Import failed. :-(
Import on start from extern adress on our fileserver as well failed.
Found out, that the exported file is formated as
**USC-2 Little Endian without BOM**.
I could not format my edited file in any of the mentioned editors to that format...
So how can I edit the xml file and re-import it? Any chance? 
Or just editable inside quicktext?
Thankful for anny answer.
CargoB from Berlin

**Comment by jobisoft** [comment] 2018-08-29 09:48
This is a duplicate of
https://github.com/thundernest/quicktext/issues/22

It is on the list, but resources are very limited at the moment.

**Closed as completed by jobisoft** 2018-08-29 09:48 UTC

**Comment by CargoB** [comment] 2018-08-29 09:49
Oh. Sorry. I will follow that one...

**Comment by jobisoft** [comment] 2018-12-18 15:35
Can you check this:
https://github.com/thundernest/quicktext/issues/22#issuecomment-448261928
