### ISSUE TITLE
Feature request: Changing the order of templates

### ISSUE THREAD

**Issue by Martin446** [thundernest/quicktext#35] opened 2018-09-25 11:27 UTC
Hello, I would like to ask you if it will be possible to add a function to change the order of existing templates or groups. I have about 100 templates in 4-5 groups and when I add some more, it is automatically set at the end of the list in selected group. But I need some of them to be on a higher position in the list because I use them more often than the others. Please help :(

**Comment by jobisoft** [comment] 2018-09-25 11:34
Duplicate of 
https://github.com/thundernest/quicktext/issues/14

**Closed as completed by jobisoft** 2018-09-25 11:34 UTC
