### ISSUE TITLE
Unable to resize window

### ISSUE THREAD

**Issue by lt-codex** [thundernest/quicktext#127] opened 2020-02-02 09:47 UTC
Hello,

I am unable to resize the window on MacOS and cannot see the text anymore. Is there something I can do to fix this? 

OS: 10.14.1 (18B75)
Thunderbird: 68.4.2 (64-bit)

<img width="1087" alt="Screen Shot 2020-02-02 at 1 45 52 AM" src="https://user-images.githubusercontent.com/40219829/73606340-f2712d80-455d-11ea-9fe2-9dce717f8d9a.png">

**Comment by jobisoft** [comment] 2020-02-02 09:49
which version of quicktext do you have?

**Comment by jobisoft** [comment] 2020-02-02 10:27
Can you check in your AddOn Manager for updates? I think I fixed this issue:

![grafik](https://user-images.githubusercontent.com/5830621/73606841-d9dd3380-45ae-11ea-8762-4e6f43bd3429.png)

I am closing this anyhow, as it is a duplicate of #125 Please report there, if it is still not fixed with Quicktext 2.12.

**Closed as completed by jobisoft** 2020-02-02 10:27 UTC

**Comment by jobisoft** [comment] 2020-02-05 07:47
@leonktam : I created a new issue specific to your setup. It looks very strange.

https://github.com/thundernest/quicktext/issues/129
