### ISSUE TITLE
Cannot move/reorder groups/templates

### ISSUE THREAD

**Issue by mamasiga** [thundernest/quicktext#14] opened 2018-06-04 13:55 UTC
Hi, I cannot change position of groups or templates within groups. Changing order by Drag'n'Drop does not work for already very long. I have Thunderbird 52.8.0 (32-bit).

**Comment by jobisoft** [comment] 2018-06-06 17:47
this is beyond my capabilities, someone else has to do that.

**Comment by spong57** [comment] 2018-06-07 10:23
Sorry this function isn't implemented yet. (I think)

**Comment by jobisoft** [comment] 2018-06-07 10:28
It was. I do not know if Emil Hesslow removed it or if the code simply does not work anymore due to changed API. I have not found anything in the current code, that looks like it is responsible for that feature. I do not have the knowledge to re-implement that feature...

**Comment by sebastianhaberey** [comment] 2018-06-07 21:11
👍 

This is indeed a pretty important feature. I'd love to help but I simply don't have any spare time currently :( sorry.

**Comment by MoGr** [comment] 2018-06-11 16:50
Dear all, we as a small company are as well heavily dependent on the "drag-and-drop" feature of the templates. Our template base has grown poorly graded and without the possibility to sort templates within groups or to change groups we are facing growing problems.
@sebastianhaberey How much time do you estimate would it take to implement the feature?
Is there a possibility to pay a developer to implement it if it is possible within a reasonable amount of time? 
@jobisoft Thanks for your input, appreciate it! Do you have any other ideas who could help us with this request?
Thanks to all!

**Comment by sebastianhaberey** [comment] 2018-06-11 19:41
@MoGr I wouldn't know since I'm not the developer. Just some guy who doesn't have enough time.

**Comment by RealRaven2000** [comment] 2018-06-14 10:02
> Is there a possibility to pay a developer to implement it if it is possible within a reasonable amount of time

@MoGr 
Ovari invited me to look at this to potentially code it - I don't use quicktext, can you describe where you need drag & drop and why?

**Comment by MoGr** [comment] 2018-06-14 14:53
@RealRaven2000 
Quicktext lets you create 'groups' of text templates, lets say our group name is "greetings". This group is displayed within the Thunderbird menu. Within that group you have your templates, for example "Dear Sir and Madame..." and then next "Thank you for your purchase...".
Now you add more and more templates into your "greetings" group and later realize you have templates within that group that do not propperly fit the "greetings" theme. You now create a second group "Customer contact" and want to drag and drop some templates from "greetings" into the new group. That does not work at the moment. Next you want to rearrange templates within one group, that is change the order, which does not work neigther.
I hope I could explain it well enough!
Feel free to download Thunderbird and Quicktest and try it yourself... Any help is appreciated! Thanks a lot!

**Comment by RealRaven2000** [comment] 2018-06-15 09:33
Ok, I just tested the QuickText Settings - you want the drag & drop working in that dialog on the "Templates" tab? Before doing that I would address some usability points.
(1) make the dialog resizable, the list is a little short for good D&D. 
(2) can the settings dialog be opened_from the Composer window_  and be made non-modal? This way you can leave the dialog open while testing your templates. (I opened the dialog from the Extensions Manager, I know there it is always modal by design)

**Comment by MoGr** [comment] 2018-06-15 12:17
@RealRaven2000 
Yes exactly! Within the "Templates" tab of the Quicktext settings I would like to D&D templates.
to (1): Great idea! Why not use the entire screen to comfortably D&D templates from one group to another or within groups...
to (2) Yes, the dialog is modal by design. A non-modal design does not give benfits in my opinion. You D&D your templates and just close the dialog to test it. If it is easier to code for you, a modal design does not harm but if it is extra work I think it is not worth the effort to make it non-modal.
Thank you so much for your offered help!

**Comment by jobisoft** [comment] 2018-06-15 12:50
While you go through the sources, if you find any non functional code or code that is there to work with older versions of thunderbird, feel free to remove it.

The current quicktext 1.1 has Thunderbird 52 as minimum requirement. 

Please keep in mind, that the API for Thunderbird is changing drastically at the moment. I strongly suggest to develop your changes with Thunderbird 60, which will turn from Beta to Stable shortly.

This maximizes the impact of your work.

**Comment by MoGr** [comment] 2018-06-22 15:12
@jobisoft: Thank's for your input!
@RealRaven2000 : Do you have any more questions that I might help you with?

**Comment by MoGr** [comment] 2018-07-16 12:31
@RealRaven2000 : Are you still involved? How is your impression? Is it possible to solve the issue? Thank you so much again!

**Comment by RealRaven2000** [comment] 2018-07-17 12:17
@MoGr just having some time constraints on my end, sorry just being busy here for the next few weeks. Probably won't have much time for cleaning up the code re Tb60. Ping me again beginning August.

**Comment by bome** [comment] 2018-09-16 10:04
Using simple buttons "up" and "down" for moving the selected template up or down might be simpler to implement and would solve all I need.

Might require a bit more clicking to fully sort your templates, but you typically don't need to reorder very often.

And/or a function to sort the templates in a group alphabetically would be great, too.

**Comment by jh20001** [comment] 2018-12-05 03:43
I def have been waiting for quite some time in hope that the ability to organize the templates/group list would come. It doesn't matter if it's drag and drop or the mentioned arrow button option. However the solution, as long as you can reorganize the list, the feature would be a game changer compared to what it is now. 

I too wonder why the previous dev removed the option some times ago. I bet @jobisoft is right, and it might have been a compatibility issue forcing them to remove the code. The dev might have never came back to it because creating a working solution was too time consuming at that time (which is also prob why someone had to take things over). 

All I know for sure, is over time my list of templates went from highly organized, to being a complete mess :)

It rocks that someone went out of their way to keep the ball moving on such a great addon!

**Comment by sebastianhaberey** [comment] 2018-12-05 14:18
For the people who really want this bugfix: you can easily set up a bounty on [Bountysource](https://www.bountysource.com/) for it to motivate developers to take on the task. I just put up a bounty for a feature on the Duplicati project and I think it's a really nice idea.

**Comment by jobisoft** [comment] 2019-01-01 10:42
User @RayCulp created a script to reorder the entries:
https://github.com/RayCulp/XSLT-to-sort-Quicktext-XML/blob/master/README.md

However, I do not know if it will work with the utf8 fileformat of the next version of quicktext:
https://github.com/thundernest/quicktext/issues/22#issuecomment-448261928

 Maybe @RayCulp can comment?

**Comment by RayCulp** [comment] 2019-01-01 12:42
I'm pretty sure it will still work. In fact, it will probably work even better. We can probably skip the step of opening the XML file with Notepad and saving it in UTF-8 encoding. The reason I had to include that step in the first place was because msxsl.exe throws an error otherwise.

**Comment by tbertels** [comment] 2019-02-03 23:25
> It was. I do not know if Emil Hesslow removed it or if the code simply does not work anymore due to changed API. I have not found anything in the current code, that looks like it is responsible for that feature. I do not have the knowledge to re-implement that feature...

It's still implemented, but indeed with an old method which may not be supported: https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Drag_and_drop/Drag_and_Drop_Example

Here's the new recommended method: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API

**Comment by sebastianhaberey** [comment] 2019-04-19 18:38
I believe I have resolved this issue. I have created a [pull request](https://github.com/thundernest/quicktext/pull/63) that can be merged by a maintainer with write access to this repository.

**Comment by jobisoft** [comment] 2019-04-19 19:43
Thanks! I merged and released 1.3, also pushed it to ATN, will be released soon I hope. It works for me on Windows. 

@everybody: Please re-open this issue, if v1.3 does not fix it for you on Linux or Mac.

**Closed as completed by jobisoft** 2019-04-19 19:43 UTC
Labels: bug, help wanted

**Comment by sebastianhaberey** [comment] 2019-04-19 19:50
Nice 👍  that was quick. I was just about to propose a new release, but then I saw that you already did it. Thanks for that!

**Comment by jobisoft** [comment] 2019-04-19 19:52
It is avail on ATN already. Looks like some reviewer was waiting for that fix as well :-)
https://addons.thunderbird.net/addon/quicktext/

**Comment by jh20001** [comment] 2019-04-19 20:18
![QuickText](https://user-images.githubusercontent.com/6210275/56443966-a47b8980-62ab-11e9-92fd-6ca71e169092.jpg)
You guys are awesome! It does seem to work great within Windows 10 and TB 60.6.1

I do notice a slight bug which isn't a show stopper if it means this working or not, but if you have a list of templates long enough for the scrollbar to form in the window, the scrollbar cannot be clicked and dragged up and down as instead it will drag around as if it was line-item in the list. However, the scroll wheel of a mouse still controls the bar just fine. 

I could freakin hug someone right now!

**Comment by epsso** [comment] 2019-04-19 20:47
Thanks.  This works great for me.

**Comment by sebastianhaberey** [comment] 2019-04-19 21:00
@jh20001 oh god you're right, that's a pretty funny bug right there! I've created another [pull request](https://github.com/thundernest/quicktext/pull/64) that should fix the draggable scrollbar issue you discovered.

**Comment by RayCulp** [comment] 2019-04-20 11:17
Works great! Thanks! :-)

**Comment by jobisoft** [comment] 2019-04-20 17:19
v1.4 is avail on ATN

**Comment by polarbearing** [comment] 2019-04-20 18:13
Confirming it works on MacOS, thanks a lot! (10.11.6/ TB 10.5.1)

**Comment by MoGr** [comment] 2019-04-23 12:33
@sebastianhaberey Thank you sooo much for solving the issue!!! Your work is a lot appreciated and will save us a lot of time in the future! Works fine on Windows 10.
@jobisoft Thank's for quickly uploading the new version!

**Comment by karlbu** [comment] 2019-05-09 19:34
OMG this is awesome!
