### ISSUE TITLE
Lost Cursor

### ISSUE THREAD

**Issue by ghost** [thundernest/quicktext#213] opened 2020-11-17 21:49 UTC
Until the latest update to TB and / Quicktext, when I inserted a Greeting or Signature by clicking on the button above the text box, the cursor appeared again at the end of the text ready to type.
Now it does not reappear, and a continued use of the Enter key reproduces the inserted text over and over.
I have to click in the text box at the end of the inserted text for the cursor to reappear.

Why is this, please?
(It is a pain!)

Thank you.

**Comment by SamuelPlentz** [comment] 2020-11-18 06:02
Duplicate of #208.

See new Testversion there.

**Comment by jobisoft** [comment] 2021-01-16 10:55
Released as v3.5.

**Closed as completed by jobisoft** 2021-01-16 10:55 UTC
